### ISSUE TITLE
Suggestion for StyledButton component

### ISSUE THREAD

**Issue by Edilsonpaio** [EtheaDev/StyledComponents#17]
I want to congratulate you on the StyledButton component. Fantastic!
I would suggest two implementations:

- Background transparency (like SpeedButton)
- Capture SVG image

I believe it would be even better with these implementations.

Edilson Paio

**Comment by carloBarazzetta** [comment]
Hello Edilson,
1) the Background transparency is available if you use TStyledGraphicButton or TStyledSpeedButton, because the inherits from TGraphicControl, but don't have TabStop and Focus, because they are only a "graphic surface".
TStyledButton and TStyledBitBtn inherites from TCustomControl that have a "windows handle" but not supports transparency, like classic TButton or TBitBtn.
2) The Glyph property is implemented into StyledButtons only for backward compatibility and the capability to "Capture SVG image" is not available. But I reccommend to use an ImageList capable to use SVG Icons (like my SVGIconImageList library), or a SVGIconImageCollection + VirtualImageList (if you have Delphi 10.4+). The you can attach the ImageList to the StyledButton or to an ActionList, so you can attach the Actions to the Action of the StyledButton.
I hope to help you...

**Comment by carloBarazzetta** [comment]
No feedback... closed.
