### ISSUE TITLE
Height of a TStyledToolButton on a tpanel

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#27]
I create a Tpanel with a TStyledToolButton without image and only a caption, with height=60. At Design time ok, but a run time the hieght of TStyledToolButton i resized at 10. Is correct ? There is a modo to force the Height as at design time ?

**Comment by carloBarazzetta** [comment]
The size of the StyledToolButton is controlled by StyledToolBar.ButtonHeight and StyledToolBar.ButtonWidth.
At design time you can resize a single ToolButton that cause the resize of all of the ToolButtons present in the Toolbar, because StyledToolBar.ButtonHeight or StyledToolBar.ButtonWidth changes.

**Comment by MAUROFAILO** [comment]
YES, BAT NOT ON A TPANEL.
