### ISSUE TITLE
Double-Clicking on TStyledButton in design time does not behave correctly

### ISSUE THREAD

**Issue by lancerasmussen** [EtheaDev/StyledComponents#30]
Standard behavior when double-clicking on a TButton or similar component is to When Double-clicking on a TButton (or similar) component is to connect or create and connect to the OnClick event so that code can be entered into the OnClick event.

Behavior of double-clicking on the TStyledButton brings up the StyledButton Editor and should not.  Right-clicking on the TStyledButton and selecting the editor behaves correct and should be the standard pathway to editing the button styling.

Test was the StyledButtonsVCLStyled demo and opening the FAboutForm form and double-clicking on the OK button.

**Comment by carloBarazzetta** [comment]
Yes Lance, the standard and absurd way is to open OnClick event, but I hate using direct OnClick event instead of using Actions... I want to discourage developers from this nonsensical approach... Do you agree with me?
I made some small choices to "break" backwards compatibility, one is this, the other is the "crHandPoint" cursor by default ;-)

**Comment by carloBarazzetta** [comment]
Can I close this issue?
