### ISSUE TITLE
Preventing Event Trigger for Disabled Button States for Better Usability

### ISSUE THREAD

**Issue by lovehyunju** [EtheaDev/StyledComponents#64]
I understand that part. My question is, generally, when a button is disabled, shouldn't it not trigger any events? Other default components also don’t trigger any events when they’re in a disabled state.

Currently, to use this component, I have to add extra code to check if the Sender is the button whenever it’s disabled. Wouldn’t it be better if no events were triggered at all in the disabled state? This would eliminate the need for additional code, making it more convenient.

https://github.com/EtheaDev/StyledComponents/issues/59

**Comment by carloBarazzetta** [comment]
No, my button works exactly as a Standard VCL Button: if you substitute in your demo the StyledButton with a TButton, you can see that when the button is disabled the event handler fires because YOU attached the same event handler to the Form, and the Form captures the OnClick event! Che the Sender inside the EventHandler ;-)

**Comment by lovehyunju** [comment]
I've just realized my mistake, and I apologize for any inconvenience it may have caused. 
Thank you sincerely for your assistance.
