### ISSUE TITLE
TStyledBitBtn and Wordwrap

### ISSUE THREAD

**Issue by lancerasmussen** [EtheaDev/StyledComponents#65]
The button, even with adjusted height to accommodate wrapped text, does not properly render the text.   Usually the first line of text appears ok, then the second line looks like dots or gibberish

**Comment by carloBarazzetta** [comment]
Please give me a simple example project to see the problem...

**Comment by lancerasmussen** [comment]
[StyledBitBtn.zip](https://github.com/user-attachments/files/17924927/StyledBitBtn.zip)

Included is a screenshot too

**Comment by carloBarazzetta** [comment]
I saw the bug, I never noticed it because I never use StyledBitBtn, I just created them for "backwards compatibility".
Is there a reason you use StyledBitBtns instead of StyledButtons? I personally don't like how the icons are aligned in BitBtn, which get closer to the center of the button when the caption is short...
However I will fix it as soon as possible..
